version: "3.8"
services:
  app:
    build: .
    container_name: ikabotapi
    restart: always
    networks:
      - web_network
    environment:
      - LOGS_WEBHOOK_URL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - app
networks:
  web_network:
    driver: bridge